version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: |
            echo "CIRCLE_TAG = $CIRCLE_TAG"
            export my_ver=$([ -z $CIRCLE_TAG ] || git describe --always --tags)
            echo "my_ver = $my_ver"
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
