version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          command: |
            echo "CIRCLE_TAG = $CIRCLE_TAG"
            export my_ver=$(git describe --exact-match --tags $(git log -n1 --pretty='%h') 2>/dev/null || git describe --always --tags)
            echo "my_ver = $my_ver"

