version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: define $CIRCLE_TAG if not defined
          command: |
            echo "CIRCLE_TAG = '$CIRCLE_TAG'"
            [[ -n $CIRCLE_TAG ]] || export CIRCLE_TAG=$(git describe --always --tags)
            echo "CIRCLE_TAG = '$CIRCLE_TAG'"
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: strip "v" from $CIRCLE_TAG
          command: |
            echo "CIRCLE_TAG = '$CIRCLE_TAG'"
            CIRCLE_TAG=$(echo $CIRCLE_TAG | tr -d v)
            echo "CIRCLE_TAG = '$CIRCLE_TAG'"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.+/
